name: 'Create Issue'
description: 'Create a GitHub issue with customizable content'
inputs:
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body (supports markdown)'
    required: true
  labels:
    description: 'Comma-separated list of labels'
    required: false
    default: ''
  assignees:
    description: 'Comma-separated list of assignees'
    required: false
    default: ''
  milestone:
    description: 'Milestone number'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Create issue
      uses: actions/github-script@v7
      with:
        script: |
          const title = '${{ inputs.title }}';
          const body = '${{ inputs.body }}';
          const labels = '${{ inputs.labels }}'.split(',').filter(l => l.trim());
          const assignees = '${{ inputs.assignees }}'.split(',').filter(a => a.trim());
          const milestone = '${{ inputs.milestone }}' ? parseInt('${{ inputs.milestone }}') : undefined;

          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: labels.length > 0 ? labels : undefined,
            assignees: assignees.length > 0 ? assignees : undefined,
            milestone: milestone
          });

          console.log(`Created issue: ${issue.data.html_url}`);
          core.setOutput('issue-number', issue.data.number);
          core.setOutput('issue-url', issue.data.html_url);