name: "Check Workflows and Comment"
description: "Checks if a workflow failed, posts a comment on the PR and attempts to convert the PR to draft (REST then GraphQL fallback)"
inputs:
  workflow_name:
    description: "Name of the workflow that failed"
    required: true
  command:
    description: "Command to run locally to fix the issues"
    required: true
  should_fail:
    description: "Whether to fail the job (use at workflow level)"
    required: false
    default: "true"
  github_token:
    description: "Token to use for GitHub API calls (pass a secret from the calling workflow)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Comment and convert PR to draft (REST + GraphQL fallback)
      id: comment_and_draft
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { owner, repo } = context.repo;
          const payloadPr = context.payload && context.payload.pull_request ? context.payload.pull_request : undefined;
          const prNumber = context.issue && context.issue.number
            ? context.issue.number
            : payloadPr && payloadPr.number
              ? payloadPr.number
              : undefined;

          if (!prNumber) {
            console.log('Not a PR context; skipping.');
            return;
          }

          if (process.env.JOB_STATUS !== 'failure') {
            console.log('Job did not fail; skipping.');
            return;
          }

          // Authenticated user + permission check
          try {
            const auth = await github.rest.users.getAuthenticated();
            console.log('Authenticated user:', auth.data.login);
            const perm = await github.rest.repos.getCollaboratorPermissionLevel({
              owner,
              repo,
              username: auth.data.login,
            });
            console.log('Collaborator permission level for authenticated user:', perm.data.permission);
          } catch (err) {
            console.error('Failed to get authenticated user or permission level:', err && err.message ? err.message : err);
          }

          if (payloadPr) {
            console.log('PR head repo full_name:', payloadPr.head && payloadPr.head.repo && payloadPr.head.repo.full_name);
            console.log('PR head repo fork?:', payloadPr.head && payloadPr.head.repo && payloadPr.head.repo.fork);
            console.log('PR author login:', payloadPr.user && payloadPr.user.login);
          }

          const body = [
            `## ❌ ${process.env.WORKFLOW_NAME} Failed`,
            "",
            "The workflow failed. Please run the following locally and fix all issues.",
            "",
            "```bash",
            process.env.COMMAND,
            "```",
            "",
            'Make sure all checks pass locally before marking the PR as "Ready for review".'
          ].join("\n");

          // Create comment
          try {
            await github.rest.issues.createComment({ owner, repo, issue_number: prNumber, body });
            console.log(`Comment created on PR #${prNumber}`);
          } catch (err) {
            console.error('Failed to create comment:', err && err.message ? err.message : err);
            throw err;
          }

          // Get PR via REST
          let pr;
          try {
            const getRes = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
            pr = getRes.data;
            console.log('PR draft status before update:', pr.draft);
          } catch (err) {
            console.error('Failed to get PR:', err && err.message ? err.message : err);
            throw err;
          }

          // Try REST update first
          try {
            if (!pr.draft) {
              const res = await github.rest.pulls.update({ owner, repo, pull_number: prNumber, draft: true });
              console.log('pulls.update HTTP status:', res.status);
              console.log('pulls.update response draft value:', res.data.draft);
              if (res.data.draft === true) {
                console.log('PR converted to draft via REST.');
                return;
              }
              console.log('REST update did not set draft to true; attempting GraphQL fallback.');
            } else {
              console.log('PR already in draft mode; no update needed.');
              return;
            }
          } catch (err) {
            console.error('REST pulls.update failed:', err && err.message ? err.message : err);
            // continue to GraphQL fallback
          }

          // GraphQL fallback: convertPullRequestToDraft
          try {
            const prNodeId = pr.node_id;
            if (!prNodeId) {
              console.error('No node_id available for PR; cannot perform GraphQL mutation.');
            } else {
              const mutation = `
                mutation ConvertToDraft($id: ID!) {
                  convertPullRequestToDraft(input: { pullRequestId: $id }) {
                    clientMutationId
                    pullRequest {
                      number
                      isDraft
                      id
                    }
                  }
                }
              `;
              const gqlRes = await github.graphql(mutation, { id: prNodeId });
              console.log('GraphQL convertPullRequestToDraft result:', JSON.stringify(gqlRes, null, 2));
              const converted = gqlRes && gqlRes.convertPullRequestToDraft && gqlRes.convertPullRequestToDraft.pullRequest && gqlRes.convertPullRequestToDraft.pullRequest.isDraft;
              if (converted === true) {
                console.log('PR converted to draft via GraphQL.');
                return;
              } else {
                console.log('GraphQL mutation did not set isDraft true. Inspect the returned object above.');
              }
            }
          } catch (err) {
            console.error('GraphQL convertPullRequestToDraft failed:', err && err.message ? err.message : err);
          }

          console.error('Both REST and GraphQL attempts finished; PR was not marked as draft. If both returned without error but draft is still false, contact GitHub Support or try manually converting in the web UI.');
      env:
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
        COMMAND: ${{ inputs.command }}
        JOB_STATUS: ${{ job.status }}

    - name: Optionally fail the job
      shell: bash
      run: |
        if [ "${{ inputs.should_fail }}" = "true" ] && [ "${{ job.status }}" = "failure" ]; then
          exit 1
        fi
