name: "Check Workflows and Comment"
description: "Checks if workflow failed and comments + converts PR to draft"
inputs:
  workflow_name:
    description: "Name of the workflow that failed"
    required: true
  command:
    description: "Command to run locally to fix the issues"
    required: true
  should_fail:
    description: "Whether to fail the job (use at workflow level)"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Comment and convert PR to draft
      id: comment_and_draft
      uses: actions/github-script@v7
      env:
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
        COMMAND: ${{ inputs.command }}
        JOB_STATUS: ${{ job.status }}
      with:
        script: |
          const { owner, repo } = context.repo;
          const prNumber = context.issue.number;
          if (!prNumber) {
            core.info('Not a PR context; skipping.');
            return;
          }
          if (process.env.JOB_STATUS !== 'failure') {
            core.info('Job did not fail; skipping.');
            return;
          }
          const body = [
            `## ❌ ${process.env.WORKFLOW_NAME} Failed`,
            "",
            "The workflow failed. Please run the following locally and fix all issues.",
            "",
            "```bash",
            process.env.COMMAND,
            "```",
            "",
            'Make sure all checks pass locally before marking the PR as "Ready for review".'
          ].join("\n");
          await github.rest.issues.createComment({ owner, repo, issue_number: prNumber, body });
          const pr = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
          if (!pr.data.draft) {
            await github.rest.pulls.update({ owner, repo, pull_number: prNumber, draft: true });
          }
    - name: Optionally fail the job
      shell: bash
      run: |
        if [ "${{ inputs.should_fail }}" = "true" ] && [ "${{ job.status }}" = "failure" ]; then
          exit 1
        fi
