version: "3.8"

services:
  redis:
    image: docker.io/library/redis:7-alpine
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

  db:
    image: docker.io/postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: docker.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: content-writer
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  chroma:
    image: docker.io/chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/data
volumes:
  pgdata:
  miniodata:
  chroma-data:
  redisdata:
