/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAnonymousRouteImport } from './routes/auth/anonymous'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known.openid-configuration'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthSignInEmailRouteImport } from './routes/auth/sign-in/email'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSlugOnboardingRouteImport } from './routes/_authenticated/$slug/onboarding'
import { Route as AuthenticatedSlugTeamIdRouteImport } from './routes/_authenticated/$slug/$teamId'
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from './routes/[.]well-known.oauth-authorization-server.$'
import { Route as AuthenticatedSlugTeamIdEditorRouteImport } from './routes/_authenticated/$slug/$teamId/_editor'
import { Route as AuthenticatedSlugTeamIdDashboardRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard'
import { Route as AuthenticatedSlugTeamIdEditorContentIdRouteImport } from './routes/_authenticated/$slug/$teamId/_editor/$contentId'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings'
import { Route as AuthenticatedSlugTeamIdDashboardPlansRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/plans'
import { Route as AuthenticatedSlugTeamIdDashboardBillingRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/billing'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/index'
import { Route as AuthenticatedSlugTeamIdDashboardHomeIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/home/index'
import { Route as AuthenticatedSlugTeamIdDashboardFormsIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/forms/index'
import { Route as AuthenticatedSlugTeamIdDashboardContentIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/content/index'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsSecurityRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/security'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProfileRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/profile'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/personal-api-keys'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/feature-previews'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/danger-zone'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsCustomizationRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/customization'
import { Route as AuthenticatedSlugTeamIdDashboardFormsFormIdRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/forms/$formId'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/data-management'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/insights/index'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/index'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/index'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/webhooks'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/integrations'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/general'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/danger-zone'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/activity-logs'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/access-control'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/organization/security'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/organization/roles'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/organization/members'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/organization/general'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/organization/danger-zone'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/organization/authentication'
import { Route as AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/forms/$formId.submissions'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/insights/$insightId'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/event-definitions'
import { Route as AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/$dashboardId'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/products/forms'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/products/content'
import { Route as AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRouteImport } from './routes/_authenticated/$slug/$teamId/_dashboard/settings/project/products/ai-agents'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnonymousRoute = AuthAnonymousRouteImport.update({
  id: '/anonymous',
  path: '/anonymous',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInRoute,
} as any)
const AuthSignInEmailRoute = AuthSignInEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthSignInRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlugOnboardingRoute =
  AuthenticatedSlugOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTeamIdRoute = AuthenticatedSlugTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: '/.well-known/oauth-authorization-server/$',
    path: '/.well-known/oauth-authorization-server/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSlugTeamIdEditorRoute =
  AuthenticatedSlugTeamIdEditorRouteImport.update({
    id: '/_editor',
    getParentRoute: () => AuthenticatedSlugTeamIdRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardRoute =
  AuthenticatedSlugTeamIdDashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedSlugTeamIdRoute,
  } as any)
const AuthenticatedSlugTeamIdEditorContentIdRoute =
  AuthenticatedSlugTeamIdEditorContentIdRouteImport.update({
    id: '/$contentId',
    path: '/$contentId',
    getParentRoute: () => AuthenticatedSlugTeamIdEditorRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsRoute =
  AuthenticatedSlugTeamIdDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardPlansRoute =
  AuthenticatedSlugTeamIdDashboardPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardBillingRoute =
  AuthenticatedSlugTeamIdDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsIndexRoute =
  AuthenticatedSlugTeamIdDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardHomeIndexRoute =
  AuthenticatedSlugTeamIdDashboardHomeIndexRouteImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardFormsIndexRoute =
  AuthenticatedSlugTeamIdDashboardFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardContentIndexRoute =
  AuthenticatedSlugTeamIdDashboardContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute =
  AuthenticatedSlugTeamIdDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsProfileRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute =
  AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRouteImport.update({
    id: '/personal-api-keys',
    path: '/personal-api-keys',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute =
  AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRouteImport.update({
    id: '/feature-previews',
    path: '/feature-previews',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute =
  AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRouteImport.update({
    id: '/danger-zone',
    path: '/danger-zone',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute =
  AuthenticatedSlugTeamIdDashboardSettingsCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardFormsFormIdRoute =
  AuthenticatedSlugTeamIdDashboardFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteImport.update({
    id: '/analytics/data-management',
    path: '/analytics/data-management',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRouteImport.update({
    id: '/analytics/insights/',
    path: '/analytics/insights/',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRouteImport.update({
    id: '/analytics/dashboards/',
    path: '/analytics/dashboards/',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRouteImport.update({
    id: '/project/webhooks',
    path: '/project/webhooks',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRouteImport.update(
    {
      id: '/project/integrations',
      path: '/project/integrations',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRouteImport.update({
    id: '/project/general',
    path: '/project/general',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRouteImport.update({
    id: '/project/danger-zone',
    path: '/project/danger-zone',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRouteImport.update(
    {
      id: '/project/activity-logs',
      path: '/project/activity-logs',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRouteImport.update(
    {
      id: '/project/access-control',
      path: '/project/access-control',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute =
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRouteImport.update(
    {
      id: '/organization/security',
      path: '/organization/security',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute =
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRouteImport.update({
    id: '/organization/roles',
    path: '/organization/roles',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute =
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRouteImport.update(
    {
      id: '/organization/members',
      path: '/organization/members',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute =
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRouteImport.update(
    {
      id: '/organization/general',
      path: '/organization/general',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute =
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRouteImport.update(
    {
      id: '/organization/danger-zone',
      path: '/organization/danger-zone',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute =
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRouteImport.update(
    {
      id: '/organization/authentication',
      path: '/organization/authentication',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute =
  AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardFormsFormIdRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRouteImport.update({
    id: '/analytics/insights/$insightId',
    path: '/analytics/insights/$insightId',
    getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
  } as any)
const AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRouteImport.update(
    {
      id: '/event-definitions',
      path: '/event-definitions',
      getParentRoute: () =>
        AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute =
  AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRouteImport.update(
    {
      id: '/analytics/dashboards/$dashboardId',
      path: '/analytics/dashboards/$dashboardId',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRouteImport.update(
    {
      id: '/project/products/forms',
      path: '/project/products/forms',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRouteImport.update(
    {
      id: '/project/products/content',
      path: '/project/products/content',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )
const AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute =
  AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRouteImport.update(
    {
      id: '/project/products/ai-agents',
      path: '/project/products/ai-agents',
      getParentRoute: () => AuthenticatedSlugTeamIdDashboardSettingsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/$slug/$teamId': typeof AuthenticatedSlugTeamIdEditorRouteWithChildren
  '/$slug/onboarding': typeof AuthenticatedSlugOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/$slug/$teamId/billing': typeof AuthenticatedSlugTeamIdDashboardBillingRoute
  '/$slug/$teamId/plans': typeof AuthenticatedSlugTeamIdDashboardPlansRoute
  '/$slug/$teamId/settings': typeof AuthenticatedSlugTeamIdDashboardSettingsRouteWithChildren
  '/$slug/$teamId/$contentId': typeof AuthenticatedSlugTeamIdEditorContentIdRoute
  '/$slug/$teamId/analytics/data-management': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteWithChildren
  '/$slug/$teamId/forms/$formId': typeof AuthenticatedSlugTeamIdDashboardFormsFormIdRouteWithChildren
  '/$slug/$teamId/settings/customization': typeof AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute
  '/$slug/$teamId/settings/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute
  '/$slug/$teamId/settings/feature-previews': typeof AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute
  '/$slug/$teamId/settings/personal-api-keys': typeof AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute
  '/$slug/$teamId/settings/profile': typeof AuthenticatedSlugTeamIdDashboardSettingsProfileRoute
  '/$slug/$teamId/settings/security': typeof AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute
  '/$slug/$teamId/content/': typeof AuthenticatedSlugTeamIdDashboardContentIndexRoute
  '/$slug/$teamId/forms/': typeof AuthenticatedSlugTeamIdDashboardFormsIndexRoute
  '/$slug/$teamId/home/': typeof AuthenticatedSlugTeamIdDashboardHomeIndexRoute
  '/$slug/$teamId/settings/': typeof AuthenticatedSlugTeamIdDashboardSettingsIndexRoute
  '/$slug/$teamId/analytics/dashboards/$dashboardId': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute
  '/$slug/$teamId/analytics/data-management/event-definitions': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute
  '/$slug/$teamId/analytics/insights/$insightId': typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute
  '/$slug/$teamId/forms/$formId/submissions': typeof AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute
  '/$slug/$teamId/settings/organization/authentication': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute
  '/$slug/$teamId/settings/organization/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute
  '/$slug/$teamId/settings/organization/general': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute
  '/$slug/$teamId/settings/organization/members': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute
  '/$slug/$teamId/settings/organization/roles': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute
  '/$slug/$teamId/settings/organization/security': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute
  '/$slug/$teamId/settings/project/access-control': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute
  '/$slug/$teamId/settings/project/activity-logs': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute
  '/$slug/$teamId/settings/project/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute
  '/$slug/$teamId/settings/project/general': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute
  '/$slug/$teamId/settings/project/integrations': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute
  '/$slug/$teamId/settings/project/webhooks': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute
  '/$slug/$teamId/analytics/dashboards/': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute
  '/$slug/$teamId/analytics/data-management/': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute
  '/$slug/$teamId/analytics/insights/': typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute
  '/$slug/$teamId/settings/project/products/ai-agents': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute
  '/$slug/$teamId/settings/project/products/content': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute
  '/$slug/$teamId/settings/project/products/forms': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/$slug/$teamId': typeof AuthenticatedSlugTeamIdEditorRouteWithChildren
  '/$slug/onboarding': typeof AuthenticatedSlugOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/$slug/$teamId/billing': typeof AuthenticatedSlugTeamIdDashboardBillingRoute
  '/$slug/$teamId/plans': typeof AuthenticatedSlugTeamIdDashboardPlansRoute
  '/$slug/$teamId/$contentId': typeof AuthenticatedSlugTeamIdEditorContentIdRoute
  '/$slug/$teamId/forms/$formId': typeof AuthenticatedSlugTeamIdDashboardFormsFormIdRouteWithChildren
  '/$slug/$teamId/settings/customization': typeof AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute
  '/$slug/$teamId/settings/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute
  '/$slug/$teamId/settings/feature-previews': typeof AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute
  '/$slug/$teamId/settings/personal-api-keys': typeof AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute
  '/$slug/$teamId/settings/profile': typeof AuthenticatedSlugTeamIdDashboardSettingsProfileRoute
  '/$slug/$teamId/settings/security': typeof AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute
  '/$slug/$teamId/content': typeof AuthenticatedSlugTeamIdDashboardContentIndexRoute
  '/$slug/$teamId/forms': typeof AuthenticatedSlugTeamIdDashboardFormsIndexRoute
  '/$slug/$teamId/home': typeof AuthenticatedSlugTeamIdDashboardHomeIndexRoute
  '/$slug/$teamId/settings': typeof AuthenticatedSlugTeamIdDashboardSettingsIndexRoute
  '/$slug/$teamId/analytics/dashboards/$dashboardId': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute
  '/$slug/$teamId/analytics/data-management/event-definitions': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute
  '/$slug/$teamId/analytics/insights/$insightId': typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute
  '/$slug/$teamId/forms/$formId/submissions': typeof AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute
  '/$slug/$teamId/settings/organization/authentication': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute
  '/$slug/$teamId/settings/organization/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute
  '/$slug/$teamId/settings/organization/general': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute
  '/$slug/$teamId/settings/organization/members': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute
  '/$slug/$teamId/settings/organization/roles': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute
  '/$slug/$teamId/settings/organization/security': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute
  '/$slug/$teamId/settings/project/access-control': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute
  '/$slug/$teamId/settings/project/activity-logs': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute
  '/$slug/$teamId/settings/project/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute
  '/$slug/$teamId/settings/project/general': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute
  '/$slug/$teamId/settings/project/integrations': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute
  '/$slug/$teamId/settings/project/webhooks': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute
  '/$slug/$teamId/analytics/dashboards': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute
  '/$slug/$teamId/analytics/data-management': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute
  '/$slug/$teamId/analytics/insights': typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute
  '/$slug/$teamId/settings/project/products/ai-agents': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute
  '/$slug/$teamId/settings/project/products/content': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute
  '/$slug/$teamId/settings/project/products/forms': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/_authenticated/$slug/$teamId': typeof AuthenticatedSlugTeamIdRouteWithChildren
  '/_authenticated/$slug/onboarding': typeof AuthenticatedSlugOnboardingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard': typeof AuthenticatedSlugTeamIdDashboardRouteWithChildren
  '/_authenticated/$slug/$teamId/_editor': typeof AuthenticatedSlugTeamIdEditorRouteWithChildren
  '/_authenticated/$slug/$teamId/_dashboard/billing': typeof AuthenticatedSlugTeamIdDashboardBillingRoute
  '/_authenticated/$slug/$teamId/_dashboard/plans': typeof AuthenticatedSlugTeamIdDashboardPlansRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings': typeof AuthenticatedSlugTeamIdDashboardSettingsRouteWithChildren
  '/_authenticated/$slug/$teamId/_editor/$contentId': typeof AuthenticatedSlugTeamIdEditorContentIdRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteWithChildren
  '/_authenticated/$slug/$teamId/_dashboard/forms/$formId': typeof AuthenticatedSlugTeamIdDashboardFormsFormIdRouteWithChildren
  '/_authenticated/$slug/$teamId/_dashboard/settings/customization': typeof AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/feature-previews': typeof AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/personal-api-keys': typeof AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/profile': typeof AuthenticatedSlugTeamIdDashboardSettingsProfileRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/security': typeof AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute
  '/_authenticated/$slug/$teamId/_dashboard/content/': typeof AuthenticatedSlugTeamIdDashboardContentIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/forms/': typeof AuthenticatedSlugTeamIdDashboardFormsIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/home/': typeof AuthenticatedSlugTeamIdDashboardHomeIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/': typeof AuthenticatedSlugTeamIdDashboardSettingsIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/$dashboardId': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/event-definitions': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/$insightId': typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute
  '/_authenticated/$slug/$teamId/_dashboard/forms/$formId/submissions': typeof AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/organization/authentication': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/organization/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/organization/general': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/organization/members': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/organization/roles': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/organization/security': typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/access-control': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/activity-logs': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/danger-zone': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/general': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/integrations': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/webhooks': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/': typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/': typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/ai-agents': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/content': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute
  '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/forms': typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/.well-known/openid-configuration'
    | '/$slug'
    | '/api/$'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/$slug/$teamId'
    | '/$slug/onboarding'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/$slug/$teamId/billing'
    | '/$slug/$teamId/plans'
    | '/$slug/$teamId/settings'
    | '/$slug/$teamId/$contentId'
    | '/$slug/$teamId/analytics/data-management'
    | '/$slug/$teamId/forms/$formId'
    | '/$slug/$teamId/settings/customization'
    | '/$slug/$teamId/settings/danger-zone'
    | '/$slug/$teamId/settings/feature-previews'
    | '/$slug/$teamId/settings/personal-api-keys'
    | '/$slug/$teamId/settings/profile'
    | '/$slug/$teamId/settings/security'
    | '/$slug/$teamId/content/'
    | '/$slug/$teamId/forms/'
    | '/$slug/$teamId/home/'
    | '/$slug/$teamId/settings/'
    | '/$slug/$teamId/analytics/dashboards/$dashboardId'
    | '/$slug/$teamId/analytics/data-management/event-definitions'
    | '/$slug/$teamId/analytics/insights/$insightId'
    | '/$slug/$teamId/forms/$formId/submissions'
    | '/$slug/$teamId/settings/organization/authentication'
    | '/$slug/$teamId/settings/organization/danger-zone'
    | '/$slug/$teamId/settings/organization/general'
    | '/$slug/$teamId/settings/organization/members'
    | '/$slug/$teamId/settings/organization/roles'
    | '/$slug/$teamId/settings/organization/security'
    | '/$slug/$teamId/settings/project/access-control'
    | '/$slug/$teamId/settings/project/activity-logs'
    | '/$slug/$teamId/settings/project/danger-zone'
    | '/$slug/$teamId/settings/project/general'
    | '/$slug/$teamId/settings/project/integrations'
    | '/$slug/$teamId/settings/project/webhooks'
    | '/$slug/$teamId/analytics/dashboards/'
    | '/$slug/$teamId/analytics/data-management/'
    | '/$slug/$teamId/analytics/insights/'
    | '/$slug/$teamId/settings/project/products/ai-agents'
    | '/$slug/$teamId/settings/project/products/content'
    | '/$slug/$teamId/settings/project/products/forms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/.well-known/openid-configuration'
    | '/$slug'
    | '/api/$'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-up'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/$slug/$teamId'
    | '/$slug/onboarding'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/auth/sign-in/email'
    | '/auth/sign-in'
    | '/$slug/$teamId/billing'
    | '/$slug/$teamId/plans'
    | '/$slug/$teamId/$contentId'
    | '/$slug/$teamId/forms/$formId'
    | '/$slug/$teamId/settings/customization'
    | '/$slug/$teamId/settings/danger-zone'
    | '/$slug/$teamId/settings/feature-previews'
    | '/$slug/$teamId/settings/personal-api-keys'
    | '/$slug/$teamId/settings/profile'
    | '/$slug/$teamId/settings/security'
    | '/$slug/$teamId/content'
    | '/$slug/$teamId/forms'
    | '/$slug/$teamId/home'
    | '/$slug/$teamId/settings'
    | '/$slug/$teamId/analytics/dashboards/$dashboardId'
    | '/$slug/$teamId/analytics/data-management/event-definitions'
    | '/$slug/$teamId/analytics/insights/$insightId'
    | '/$slug/$teamId/forms/$formId/submissions'
    | '/$slug/$teamId/settings/organization/authentication'
    | '/$slug/$teamId/settings/organization/danger-zone'
    | '/$slug/$teamId/settings/organization/general'
    | '/$slug/$teamId/settings/organization/members'
    | '/$slug/$teamId/settings/organization/roles'
    | '/$slug/$teamId/settings/organization/security'
    | '/$slug/$teamId/settings/project/access-control'
    | '/$slug/$teamId/settings/project/activity-logs'
    | '/$slug/$teamId/settings/project/danger-zone'
    | '/$slug/$teamId/settings/project/general'
    | '/$slug/$teamId/settings/project/integrations'
    | '/$slug/$teamId/settings/project/webhooks'
    | '/$slug/$teamId/analytics/dashboards'
    | '/$slug/$teamId/analytics/data-management'
    | '/$slug/$teamId/analytics/insights'
    | '/$slug/$teamId/settings/project/products/ai-agents'
    | '/$slug/$teamId/settings/project/products/content'
    | '/$slug/$teamId/settings/project/products/forms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/.well-known/openid-configuration'
    | '/_authenticated/$slug'
    | '/api/$'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/_authenticated/$slug/$teamId'
    | '/_authenticated/$slug/onboarding'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/_authenticated/$slug/$teamId/_dashboard'
    | '/_authenticated/$slug/$teamId/_editor'
    | '/_authenticated/$slug/$teamId/_dashboard/billing'
    | '/_authenticated/$slug/$teamId/_dashboard/plans'
    | '/_authenticated/$slug/$teamId/_dashboard/settings'
    | '/_authenticated/$slug/$teamId/_editor/$contentId'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management'
    | '/_authenticated/$slug/$teamId/_dashboard/forms/$formId'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/customization'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/danger-zone'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/feature-previews'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/personal-api-keys'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/profile'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/security'
    | '/_authenticated/$slug/$teamId/_dashboard/content/'
    | '/_authenticated/$slug/$teamId/_dashboard/forms/'
    | '/_authenticated/$slug/$teamId/_dashboard/home/'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/$dashboardId'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/event-definitions'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/$insightId'
    | '/_authenticated/$slug/$teamId/_dashboard/forms/$formId/submissions'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/organization/authentication'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/organization/danger-zone'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/organization/general'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/organization/members'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/organization/roles'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/organization/security'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/access-control'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/activity-logs'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/danger-zone'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/general'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/integrations'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/webhooks'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/'
    | '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/ai-agents'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/content'
    | '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/forms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiSplatRoute: typeof ApiSplatRoute
  OauthConsentRoute: typeof OauthConsentRoute
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/anonymous': {
      id: '/auth/anonymous'
      path: '/anonymous'
      fullPath: '/auth/anonymous'
      preLoaderRoute: typeof AuthAnonymousRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/auth/sign-in/email': {
      id: '/auth/sign-in/email'
      path: '/email'
      fullPath: '/auth/sign-in/email'
      preLoaderRoute: typeof AuthSignInEmailRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug/onboarding': {
      id: '/_authenticated/$slug/onboarding'
      path: '/onboarding'
      fullPath: '/$slug/onboarding'
      preLoaderRoute: typeof AuthenticatedSlugOnboardingRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/$teamId': {
      id: '/_authenticated/$slug/$teamId'
      path: '/$teamId'
      fullPath: '/$slug/$teamId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/.well-known/oauth-authorization-server/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug/$teamId/_editor': {
      id: '/_authenticated/$slug/$teamId/_editor'
      path: ''
      fullPath: '/$slug/$teamId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdEditorRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard': {
      id: '/_authenticated/$slug/$teamId/_dashboard'
      path: ''
      fullPath: '/$slug/$teamId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdRoute
    }
    '/_authenticated/$slug/$teamId/_editor/$contentId': {
      id: '/_authenticated/$slug/$teamId/_editor/$contentId'
      path: '/$contentId'
      fullPath: '/$slug/$teamId/$contentId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdEditorContentIdRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdEditorRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings'
      path: '/settings'
      fullPath: '/$slug/$teamId/settings'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/plans': {
      id: '/_authenticated/$slug/$teamId/_dashboard/plans'
      path: '/plans'
      fullPath: '/$slug/$teamId/plans'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardPlansRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/billing': {
      id: '/_authenticated/$slug/$teamId/_dashboard/billing'
      path: '/billing'
      fullPath: '/$slug/$teamId/billing'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/'
      path: '/'
      fullPath: '/$slug/$teamId/settings/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/home/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/home/'
      path: '/home'
      fullPath: '/$slug/$teamId/home/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardHomeIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/forms/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/forms/'
      path: '/forms'
      fullPath: '/$slug/$teamId/forms/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardFormsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/content/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/content/'
      path: '/content'
      fullPath: '/$slug/$teamId/content/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardContentIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/security': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/security'
      path: '/security'
      fullPath: '/$slug/$teamId/settings/security'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/profile': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/$slug/$teamId/settings/profile'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/personal-api-keys': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/personal-api-keys'
      path: '/personal-api-keys'
      fullPath: '/$slug/$teamId/settings/personal-api-keys'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/feature-previews': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/feature-previews'
      path: '/feature-previews'
      fullPath: '/$slug/$teamId/settings/feature-previews'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/danger-zone': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/$slug/$teamId/settings/danger-zone'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/customization': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/customization'
      path: '/customization'
      fullPath: '/$slug/$teamId/settings/customization'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsCustomizationRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/forms/$formId': {
      id: '/_authenticated/$slug/$teamId/_dashboard/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/$slug/$teamId/forms/$formId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardFormsFormIdRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management'
      path: '/analytics/data-management'
      fullPath: '/$slug/$teamId/analytics/data-management'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/'
      path: '/analytics/insights'
      fullPath: '/$slug/$teamId/analytics/insights/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/'
      path: '/'
      fullPath: '/$slug/$teamId/analytics/data-management/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/'
      path: '/analytics/dashboards'
      fullPath: '/$slug/$teamId/analytics/dashboards/'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/webhooks': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/webhooks'
      path: '/project/webhooks'
      fullPath: '/$slug/$teamId/settings/project/webhooks'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/integrations': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/integrations'
      path: '/project/integrations'
      fullPath: '/$slug/$teamId/settings/project/integrations'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/general': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/general'
      path: '/project/general'
      fullPath: '/$slug/$teamId/settings/project/general'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/danger-zone': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/danger-zone'
      path: '/project/danger-zone'
      fullPath: '/$slug/$teamId/settings/project/danger-zone'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/activity-logs': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/activity-logs'
      path: '/project/activity-logs'
      fullPath: '/$slug/$teamId/settings/project/activity-logs'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/access-control': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/access-control'
      path: '/project/access-control'
      fullPath: '/$slug/$teamId/settings/project/access-control'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/organization/security': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/organization/security'
      path: '/organization/security'
      fullPath: '/$slug/$teamId/settings/organization/security'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/organization/roles': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/organization/roles'
      path: '/organization/roles'
      fullPath: '/$slug/$teamId/settings/organization/roles'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/organization/members': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/organization/members'
      path: '/organization/members'
      fullPath: '/$slug/$teamId/settings/organization/members'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/organization/general': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/organization/general'
      path: '/organization/general'
      fullPath: '/$slug/$teamId/settings/organization/general'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/organization/danger-zone': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/organization/danger-zone'
      path: '/organization/danger-zone'
      fullPath: '/$slug/$teamId/settings/organization/danger-zone'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/organization/authentication': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/organization/authentication'
      path: '/organization/authentication'
      fullPath: '/$slug/$teamId/settings/organization/authentication'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/forms/$formId/submissions': {
      id: '/_authenticated/$slug/$teamId/_dashboard/forms/$formId/submissions'
      path: '/submissions'
      fullPath: '/$slug/$teamId/forms/$formId/submissions'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardFormsFormIdRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/$insightId': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/insights/$insightId'
      path: '/analytics/insights/$insightId'
      fullPath: '/$slug/$teamId/analytics/insights/$insightId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/event-definitions': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/data-management/event-definitions'
      path: '/event-definitions'
      fullPath: '/$slug/$teamId/analytics/data-management/event-definitions'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/$dashboardId': {
      id: '/_authenticated/$slug/$teamId/_dashboard/analytics/dashboards/$dashboardId'
      path: '/analytics/dashboards/$dashboardId'
      fullPath: '/$slug/$teamId/analytics/dashboards/$dashboardId'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/forms': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/forms'
      path: '/project/products/forms'
      fullPath: '/$slug/$teamId/settings/project/products/forms'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/content': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/content'
      path: '/project/products/content'
      fullPath: '/$slug/$teamId/settings/project/products/content'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
    '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/ai-agents': {
      id: '/_authenticated/$slug/$teamId/_dashboard/settings/project/products/ai-agents'
      path: '/project/products/ai-agents'
      fullPath: '/$slug/$teamId/settings/project/products/ai-agents'
      preLoaderRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRouteImport
      parentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRoute
    }
  }
}

interface AuthenticatedSlugTeamIdDashboardSettingsRouteChildren {
  AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute
  AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute
  AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute
  AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute
  AuthenticatedSlugTeamIdDashboardSettingsProfileRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProfileRoute
  AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute
  AuthenticatedSlugTeamIdDashboardSettingsIndexRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsIndexRoute
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute
  AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute
  AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute
}

const AuthenticatedSlugTeamIdDashboardSettingsRouteChildren: AuthenticatedSlugTeamIdDashboardSettingsRouteChildren =
  {
    AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute:
      AuthenticatedSlugTeamIdDashboardSettingsCustomizationRoute,
    AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute:
      AuthenticatedSlugTeamIdDashboardSettingsDangerZoneRoute,
    AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute:
      AuthenticatedSlugTeamIdDashboardSettingsFeaturePreviewsRoute,
    AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute:
      AuthenticatedSlugTeamIdDashboardSettingsPersonalApiKeysRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProfileRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProfileRoute,
    AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute:
      AuthenticatedSlugTeamIdDashboardSettingsSecurityRoute,
    AuthenticatedSlugTeamIdDashboardSettingsIndexRoute:
      AuthenticatedSlugTeamIdDashboardSettingsIndexRoute,
    AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute:
      AuthenticatedSlugTeamIdDashboardSettingsOrganizationAuthenticationRoute,
    AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute:
      AuthenticatedSlugTeamIdDashboardSettingsOrganizationDangerZoneRoute,
    AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute:
      AuthenticatedSlugTeamIdDashboardSettingsOrganizationGeneralRoute,
    AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute:
      AuthenticatedSlugTeamIdDashboardSettingsOrganizationMembersRoute,
    AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute:
      AuthenticatedSlugTeamIdDashboardSettingsOrganizationRolesRoute,
    AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute:
      AuthenticatedSlugTeamIdDashboardSettingsOrganizationSecurityRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectAccessControlRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectActivityLogsRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectDangerZoneRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectGeneralRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectIntegrationsRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectWebhooksRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectProductsAiAgentsRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectProductsContentRoute,
    AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute:
      AuthenticatedSlugTeamIdDashboardSettingsProjectProductsFormsRoute,
  }

const AuthenticatedSlugTeamIdDashboardSettingsRouteWithChildren =
  AuthenticatedSlugTeamIdDashboardSettingsRoute._addFileChildren(
    AuthenticatedSlugTeamIdDashboardSettingsRouteChildren,
  )

interface AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteChildren {
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute
}

const AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteChildren: AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteChildren =
  {
    AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementEventDefinitionsRoute,
    AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementIndexRoute,
  }

const AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteWithChildren =
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute._addFileChildren(
    AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteChildren,
  )

interface AuthenticatedSlugTeamIdDashboardFormsFormIdRouteChildren {
  AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute: typeof AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute
}

const AuthenticatedSlugTeamIdDashboardFormsFormIdRouteChildren: AuthenticatedSlugTeamIdDashboardFormsFormIdRouteChildren =
  {
    AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute:
      AuthenticatedSlugTeamIdDashboardFormsFormIdSubmissionsRoute,
  }

const AuthenticatedSlugTeamIdDashboardFormsFormIdRouteWithChildren =
  AuthenticatedSlugTeamIdDashboardFormsFormIdRoute._addFileChildren(
    AuthenticatedSlugTeamIdDashboardFormsFormIdRouteChildren,
  )

interface AuthenticatedSlugTeamIdDashboardRouteChildren {
  AuthenticatedSlugTeamIdDashboardBillingRoute: typeof AuthenticatedSlugTeamIdDashboardBillingRoute
  AuthenticatedSlugTeamIdDashboardPlansRoute: typeof AuthenticatedSlugTeamIdDashboardPlansRoute
  AuthenticatedSlugTeamIdDashboardSettingsRoute: typeof AuthenticatedSlugTeamIdDashboardSettingsRouteWithChildren
  AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteWithChildren
  AuthenticatedSlugTeamIdDashboardFormsFormIdRoute: typeof AuthenticatedSlugTeamIdDashboardFormsFormIdRouteWithChildren
  AuthenticatedSlugTeamIdDashboardContentIndexRoute: typeof AuthenticatedSlugTeamIdDashboardContentIndexRoute
  AuthenticatedSlugTeamIdDashboardFormsIndexRoute: typeof AuthenticatedSlugTeamIdDashboardFormsIndexRoute
  AuthenticatedSlugTeamIdDashboardHomeIndexRoute: typeof AuthenticatedSlugTeamIdDashboardHomeIndexRoute
  AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute
  AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute
  AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute
  AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute: typeof AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute
}

const AuthenticatedSlugTeamIdDashboardRouteChildren: AuthenticatedSlugTeamIdDashboardRouteChildren =
  {
    AuthenticatedSlugTeamIdDashboardBillingRoute:
      AuthenticatedSlugTeamIdDashboardBillingRoute,
    AuthenticatedSlugTeamIdDashboardPlansRoute:
      AuthenticatedSlugTeamIdDashboardPlansRoute,
    AuthenticatedSlugTeamIdDashboardSettingsRoute:
      AuthenticatedSlugTeamIdDashboardSettingsRouteWithChildren,
    AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsDataManagementRouteWithChildren,
    AuthenticatedSlugTeamIdDashboardFormsFormIdRoute:
      AuthenticatedSlugTeamIdDashboardFormsFormIdRouteWithChildren,
    AuthenticatedSlugTeamIdDashboardContentIndexRoute:
      AuthenticatedSlugTeamIdDashboardContentIndexRoute,
    AuthenticatedSlugTeamIdDashboardFormsIndexRoute:
      AuthenticatedSlugTeamIdDashboardFormsIndexRoute,
    AuthenticatedSlugTeamIdDashboardHomeIndexRoute:
      AuthenticatedSlugTeamIdDashboardHomeIndexRoute,
    AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsDashboardIdRoute,
    AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsInsightsInsightIdRoute,
    AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsDashboardsIndexRoute,
    AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute:
      AuthenticatedSlugTeamIdDashboardAnalyticsInsightsIndexRoute,
  }

const AuthenticatedSlugTeamIdDashboardRouteWithChildren =
  AuthenticatedSlugTeamIdDashboardRoute._addFileChildren(
    AuthenticatedSlugTeamIdDashboardRouteChildren,
  )

interface AuthenticatedSlugTeamIdEditorRouteChildren {
  AuthenticatedSlugTeamIdEditorContentIdRoute: typeof AuthenticatedSlugTeamIdEditorContentIdRoute
}

const AuthenticatedSlugTeamIdEditorRouteChildren: AuthenticatedSlugTeamIdEditorRouteChildren =
  {
    AuthenticatedSlugTeamIdEditorContentIdRoute:
      AuthenticatedSlugTeamIdEditorContentIdRoute,
  }

const AuthenticatedSlugTeamIdEditorRouteWithChildren =
  AuthenticatedSlugTeamIdEditorRoute._addFileChildren(
    AuthenticatedSlugTeamIdEditorRouteChildren,
  )

interface AuthenticatedSlugTeamIdRouteChildren {
  AuthenticatedSlugTeamIdDashboardRoute: typeof AuthenticatedSlugTeamIdDashboardRouteWithChildren
  AuthenticatedSlugTeamIdEditorRoute: typeof AuthenticatedSlugTeamIdEditorRouteWithChildren
}

const AuthenticatedSlugTeamIdRouteChildren: AuthenticatedSlugTeamIdRouteChildren =
  {
    AuthenticatedSlugTeamIdDashboardRoute:
      AuthenticatedSlugTeamIdDashboardRouteWithChildren,
    AuthenticatedSlugTeamIdEditorRoute:
      AuthenticatedSlugTeamIdEditorRouteWithChildren,
  }

const AuthenticatedSlugTeamIdRouteWithChildren =
  AuthenticatedSlugTeamIdRoute._addFileChildren(
    AuthenticatedSlugTeamIdRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugTeamIdRoute: typeof AuthenticatedSlugTeamIdRouteWithChildren
  AuthenticatedSlugOnboardingRoute: typeof AuthenticatedSlugOnboardingRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugTeamIdRoute: AuthenticatedSlugTeamIdRouteWithChildren,
  AuthenticatedSlugOnboardingRoute: AuthenticatedSlugOnboardingRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthSignInRouteChildren {
  AuthSignInEmailRoute: typeof AuthSignInEmailRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInEmailRoute: AuthSignInEmailRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthRouteChildren {
  AuthAnonymousRoute: typeof AuthAnonymousRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnonymousRoute: AuthAnonymousRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiSplatRoute: ApiSplatRoute,
  OauthConsentRoute: OauthConsentRoute,
  DotwellKnownOauthAuthorizationServerSplatRoute:
    DotwellKnownOauthAuthorizationServerSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
