/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAnonymousRouteImport } from './routes/auth/anonymous'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known.openid-configuration'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthSignInEmailRouteImport } from './routes/auth/sign-in/email'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSlugEditorRouteImport } from './routes/_authenticated/$slug/_editor'
import { Route as AuthenticatedSlugDashboardRouteImport } from './routes/_authenticated/$slug/_dashboard'
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from './routes/[.]well-known.oauth-authorization-server.$'
import { Route as AuthenticatedSlugEditorContentIdRouteImport } from './routes/_authenticated/$slug/_editor/$contentId'
import { Route as AuthenticatedSlugDashboardSettingsRouteImport } from './routes/_authenticated/$slug/_dashboard/settings'
import { Route as AuthenticatedSlugDashboardPlansRouteImport } from './routes/_authenticated/$slug/_dashboard/plans'
import { Route as AuthenticatedSlugDashboardBillingRouteImport } from './routes/_authenticated/$slug/_dashboard/billing'
import { Route as AuthenticatedSlugDashboardSettingsIndexRouteImport } from './routes/_authenticated/$slug/_dashboard/settings/index'
import { Route as AuthenticatedSlugDashboardHomeIndexRouteImport } from './routes/_authenticated/$slug/_dashboard/home/index'
import { Route as AuthenticatedSlugDashboardContentIndexRouteImport } from './routes/_authenticated/$slug/_dashboard/content/index'
import { Route as AuthenticatedSlugDashboardSettingsSecurityRouteImport } from './routes/_authenticated/$slug/_dashboard/settings/security'
import { Route as AuthenticatedSlugDashboardSettingsProfileRouteImport } from './routes/_authenticated/$slug/_dashboard/settings/profile'
import { Route as AuthenticatedSlugDashboardSettingsPreferencesRouteImport } from './routes/_authenticated/$slug/_dashboard/settings/preferences'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnonymousRoute = AuthAnonymousRouteImport.update({
  id: '/anonymous',
  path: '/anonymous',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInRoute,
} as any)
const AuthSignInEmailRoute = AuthSignInEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthSignInRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlugEditorRoute = AuthenticatedSlugEditorRouteImport.update({
  id: '/_editor',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugDashboardRoute =
  AuthenticatedSlugDashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: '/.well-known/oauth-authorization-server/$',
    path: '/.well-known/oauth-authorization-server/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSlugEditorContentIdRoute =
  AuthenticatedSlugEditorContentIdRouteImport.update({
    id: '/$contentId',
    path: '/$contentId',
    getParentRoute: () => AuthenticatedSlugEditorRoute,
  } as any)
const AuthenticatedSlugDashboardSettingsRoute =
  AuthenticatedSlugDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSlugDashboardRoute,
  } as any)
const AuthenticatedSlugDashboardPlansRoute =
  AuthenticatedSlugDashboardPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedSlugDashboardRoute,
  } as any)
const AuthenticatedSlugDashboardBillingRoute =
  AuthenticatedSlugDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSlugDashboardRoute,
  } as any)
const AuthenticatedSlugDashboardSettingsIndexRoute =
  AuthenticatedSlugDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugDashboardHomeIndexRoute =
  AuthenticatedSlugDashboardHomeIndexRouteImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => AuthenticatedSlugDashboardRoute,
  } as any)
const AuthenticatedSlugDashboardContentIndexRoute =
  AuthenticatedSlugDashboardContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedSlugDashboardRoute,
  } as any)
const AuthenticatedSlugDashboardSettingsSecurityRoute =
  AuthenticatedSlugDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSlugDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugDashboardSettingsProfileRoute =
  AuthenticatedSlugDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSlugDashboardSettingsRoute,
  } as any)
const AuthenticatedSlugDashboardSettingsPreferencesRoute =
  AuthenticatedSlugDashboardSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSlugDashboardSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$slug': typeof AuthenticatedSlugEditorRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/$slug/billing': typeof AuthenticatedSlugDashboardBillingRoute
  '/$slug/plans': typeof AuthenticatedSlugDashboardPlansRoute
  '/$slug/settings': typeof AuthenticatedSlugDashboardSettingsRouteWithChildren
  '/$slug/$contentId': typeof AuthenticatedSlugEditorContentIdRoute
  '/$slug/settings/preferences': typeof AuthenticatedSlugDashboardSettingsPreferencesRoute
  '/$slug/settings/profile': typeof AuthenticatedSlugDashboardSettingsProfileRoute
  '/$slug/settings/security': typeof AuthenticatedSlugDashboardSettingsSecurityRoute
  '/$slug/content/': typeof AuthenticatedSlugDashboardContentIndexRoute
  '/$slug/home/': typeof AuthenticatedSlugDashboardHomeIndexRoute
  '/$slug/settings/': typeof AuthenticatedSlugDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$slug': typeof AuthenticatedSlugEditorRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/$slug/billing': typeof AuthenticatedSlugDashboardBillingRoute
  '/$slug/plans': typeof AuthenticatedSlugDashboardPlansRoute
  '/$slug/$contentId': typeof AuthenticatedSlugEditorContentIdRoute
  '/$slug/settings/preferences': typeof AuthenticatedSlugDashboardSettingsPreferencesRoute
  '/$slug/settings/profile': typeof AuthenticatedSlugDashboardSettingsProfileRoute
  '/$slug/settings/security': typeof AuthenticatedSlugDashboardSettingsSecurityRoute
  '/$slug/content': typeof AuthenticatedSlugDashboardContentIndexRoute
  '/$slug/home': typeof AuthenticatedSlugDashboardHomeIndexRoute
  '/$slug/settings': typeof AuthenticatedSlugDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/_authenticated/$slug/_dashboard': typeof AuthenticatedSlugDashboardRouteWithChildren
  '/_authenticated/$slug/_editor': typeof AuthenticatedSlugEditorRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/_authenticated/$slug/_dashboard/billing': typeof AuthenticatedSlugDashboardBillingRoute
  '/_authenticated/$slug/_dashboard/plans': typeof AuthenticatedSlugDashboardPlansRoute
  '/_authenticated/$slug/_dashboard/settings': typeof AuthenticatedSlugDashboardSettingsRouteWithChildren
  '/_authenticated/$slug/_editor/$contentId': typeof AuthenticatedSlugEditorContentIdRoute
  '/_authenticated/$slug/_dashboard/settings/preferences': typeof AuthenticatedSlugDashboardSettingsPreferencesRoute
  '/_authenticated/$slug/_dashboard/settings/profile': typeof AuthenticatedSlugDashboardSettingsProfileRoute
  '/_authenticated/$slug/_dashboard/settings/security': typeof AuthenticatedSlugDashboardSettingsSecurityRoute
  '/_authenticated/$slug/_dashboard/content/': typeof AuthenticatedSlugDashboardContentIndexRoute
  '/_authenticated/$slug/_dashboard/home/': typeof AuthenticatedSlugDashboardHomeIndexRoute
  '/_authenticated/$slug/_dashboard/settings/': typeof AuthenticatedSlugDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/.well-known/openid-configuration'
    | '/$slug'
    | '/api/$'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/$slug/billing'
    | '/$slug/plans'
    | '/$slug/settings'
    | '/$slug/$contentId'
    | '/$slug/settings/preferences'
    | '/$slug/settings/profile'
    | '/$slug/settings/security'
    | '/$slug/content/'
    | '/$slug/home/'
    | '/$slug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/.well-known/openid-configuration'
    | '/$slug'
    | '/api/$'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-up'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/auth/sign-in/email'
    | '/auth/sign-in'
    | '/$slug/billing'
    | '/$slug/plans'
    | '/$slug/$contentId'
    | '/$slug/settings/preferences'
    | '/$slug/settings/profile'
    | '/$slug/settings/security'
    | '/$slug/content'
    | '/$slug/home'
    | '/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/.well-known/openid-configuration'
    | '/_authenticated/$slug'
    | '/api/$'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/oauth/consent'
    | '/.well-known/oauth-authorization-server/$'
    | '/_authenticated/$slug/_dashboard'
    | '/_authenticated/$slug/_editor'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/_authenticated/$slug/_dashboard/billing'
    | '/_authenticated/$slug/_dashboard/plans'
    | '/_authenticated/$slug/_dashboard/settings'
    | '/_authenticated/$slug/_editor/$contentId'
    | '/_authenticated/$slug/_dashboard/settings/preferences'
    | '/_authenticated/$slug/_dashboard/settings/profile'
    | '/_authenticated/$slug/_dashboard/settings/security'
    | '/_authenticated/$slug/_dashboard/content/'
    | '/_authenticated/$slug/_dashboard/home/'
    | '/_authenticated/$slug/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiSplatRoute: typeof ApiSplatRoute
  OauthConsentRoute: typeof OauthConsentRoute
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/anonymous': {
      id: '/auth/anonymous'
      path: '/anonymous'
      fullPath: '/auth/anonymous'
      preLoaderRoute: typeof AuthAnonymousRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/auth/sign-in/email': {
      id: '/auth/sign-in/email'
      path: '/email'
      fullPath: '/auth/sign-in/email'
      preLoaderRoute: typeof AuthSignInEmailRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug/_editor': {
      id: '/_authenticated/$slug/_editor'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugEditorRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/_dashboard': {
      id: '/_authenticated/$slug/_dashboard'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/.well-known/oauth-authorization-server/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug/_editor/$contentId': {
      id: '/_authenticated/$slug/_editor/$contentId'
      path: '/$contentId'
      fullPath: '/$slug/$contentId'
      preLoaderRoute: typeof AuthenticatedSlugEditorContentIdRouteImport
      parentRoute: typeof AuthenticatedSlugEditorRoute
    }
    '/_authenticated/$slug/_dashboard/settings': {
      id: '/_authenticated/$slug/_dashboard/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthenticatedSlugDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardRoute
    }
    '/_authenticated/$slug/_dashboard/plans': {
      id: '/_authenticated/$slug/_dashboard/plans'
      path: '/plans'
      fullPath: '/$slug/plans'
      preLoaderRoute: typeof AuthenticatedSlugDashboardPlansRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardRoute
    }
    '/_authenticated/$slug/_dashboard/billing': {
      id: '/_authenticated/$slug/_dashboard/billing'
      path: '/billing'
      fullPath: '/$slug/billing'
      preLoaderRoute: typeof AuthenticatedSlugDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardRoute
    }
    '/_authenticated/$slug/_dashboard/settings/': {
      id: '/_authenticated/$slug/_dashboard/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedSlugDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardSettingsRoute
    }
    '/_authenticated/$slug/_dashboard/home/': {
      id: '/_authenticated/$slug/_dashboard/home/'
      path: '/home'
      fullPath: '/$slug/home/'
      preLoaderRoute: typeof AuthenticatedSlugDashboardHomeIndexRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardRoute
    }
    '/_authenticated/$slug/_dashboard/content/': {
      id: '/_authenticated/$slug/_dashboard/content/'
      path: '/content'
      fullPath: '/$slug/content/'
      preLoaderRoute: typeof AuthenticatedSlugDashboardContentIndexRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardRoute
    }
    '/_authenticated/$slug/_dashboard/settings/security': {
      id: '/_authenticated/$slug/_dashboard/settings/security'
      path: '/security'
      fullPath: '/$slug/settings/security'
      preLoaderRoute: typeof AuthenticatedSlugDashboardSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardSettingsRoute
    }
    '/_authenticated/$slug/_dashboard/settings/profile': {
      id: '/_authenticated/$slug/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/$slug/settings/profile'
      preLoaderRoute: typeof AuthenticatedSlugDashboardSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardSettingsRoute
    }
    '/_authenticated/$slug/_dashboard/settings/preferences': {
      id: '/_authenticated/$slug/_dashboard/settings/preferences'
      path: '/preferences'
      fullPath: '/$slug/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSlugDashboardSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedSlugDashboardSettingsRoute
    }
  }
}

interface AuthenticatedSlugDashboardSettingsRouteChildren {
  AuthenticatedSlugDashboardSettingsPreferencesRoute: typeof AuthenticatedSlugDashboardSettingsPreferencesRoute
  AuthenticatedSlugDashboardSettingsProfileRoute: typeof AuthenticatedSlugDashboardSettingsProfileRoute
  AuthenticatedSlugDashboardSettingsSecurityRoute: typeof AuthenticatedSlugDashboardSettingsSecurityRoute
  AuthenticatedSlugDashboardSettingsIndexRoute: typeof AuthenticatedSlugDashboardSettingsIndexRoute
}

const AuthenticatedSlugDashboardSettingsRouteChildren: AuthenticatedSlugDashboardSettingsRouteChildren =
  {
    AuthenticatedSlugDashboardSettingsPreferencesRoute:
      AuthenticatedSlugDashboardSettingsPreferencesRoute,
    AuthenticatedSlugDashboardSettingsProfileRoute:
      AuthenticatedSlugDashboardSettingsProfileRoute,
    AuthenticatedSlugDashboardSettingsSecurityRoute:
      AuthenticatedSlugDashboardSettingsSecurityRoute,
    AuthenticatedSlugDashboardSettingsIndexRoute:
      AuthenticatedSlugDashboardSettingsIndexRoute,
  }

const AuthenticatedSlugDashboardSettingsRouteWithChildren =
  AuthenticatedSlugDashboardSettingsRoute._addFileChildren(
    AuthenticatedSlugDashboardSettingsRouteChildren,
  )

interface AuthenticatedSlugDashboardRouteChildren {
  AuthenticatedSlugDashboardBillingRoute: typeof AuthenticatedSlugDashboardBillingRoute
  AuthenticatedSlugDashboardPlansRoute: typeof AuthenticatedSlugDashboardPlansRoute
  AuthenticatedSlugDashboardSettingsRoute: typeof AuthenticatedSlugDashboardSettingsRouteWithChildren
  AuthenticatedSlugDashboardContentIndexRoute: typeof AuthenticatedSlugDashboardContentIndexRoute
  AuthenticatedSlugDashboardHomeIndexRoute: typeof AuthenticatedSlugDashboardHomeIndexRoute
}

const AuthenticatedSlugDashboardRouteChildren: AuthenticatedSlugDashboardRouteChildren =
  {
    AuthenticatedSlugDashboardBillingRoute:
      AuthenticatedSlugDashboardBillingRoute,
    AuthenticatedSlugDashboardPlansRoute: AuthenticatedSlugDashboardPlansRoute,
    AuthenticatedSlugDashboardSettingsRoute:
      AuthenticatedSlugDashboardSettingsRouteWithChildren,
    AuthenticatedSlugDashboardContentIndexRoute:
      AuthenticatedSlugDashboardContentIndexRoute,
    AuthenticatedSlugDashboardHomeIndexRoute:
      AuthenticatedSlugDashboardHomeIndexRoute,
  }

const AuthenticatedSlugDashboardRouteWithChildren =
  AuthenticatedSlugDashboardRoute._addFileChildren(
    AuthenticatedSlugDashboardRouteChildren,
  )

interface AuthenticatedSlugEditorRouteChildren {
  AuthenticatedSlugEditorContentIdRoute: typeof AuthenticatedSlugEditorContentIdRoute
}

const AuthenticatedSlugEditorRouteChildren: AuthenticatedSlugEditorRouteChildren =
  {
    AuthenticatedSlugEditorContentIdRoute:
      AuthenticatedSlugEditorContentIdRoute,
  }

const AuthenticatedSlugEditorRouteWithChildren =
  AuthenticatedSlugEditorRoute._addFileChildren(
    AuthenticatedSlugEditorRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugDashboardRoute: typeof AuthenticatedSlugDashboardRouteWithChildren
  AuthenticatedSlugEditorRoute: typeof AuthenticatedSlugEditorRouteWithChildren
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugDashboardRoute: AuthenticatedSlugDashboardRouteWithChildren,
  AuthenticatedSlugEditorRoute: AuthenticatedSlugEditorRouteWithChildren,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthSignInRouteChildren {
  AuthSignInEmailRoute: typeof AuthSignInEmailRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInEmailRoute: AuthSignInEmailRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthRouteChildren {
  AuthAnonymousRoute: typeof AuthAnonymousRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnonymousRoute: AuthAnonymousRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiSplatRoute: ApiSplatRoute,
  OauthConsentRoute: OauthConsentRoute,
  DotwellKnownOauthAuthorizationServerSplatRoute:
    DotwellKnownOauthAuthorizationServerSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
