name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - UI/UX Bug
        - Functional Bug
        - Performance Issue
        - Security Vulnerability
        - Compatibility Issue
        - Data Corruption
        - Crash/Exception
        - Configuration Issue
        - Documentation Bug
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope-app
    attributes:
      label: App Scope
      description: Which app is affected by this bug?
      options:
        - blog
        - dashboard
        - docs
        - landing-page
        - server
        - Multiple Apps
        - Unknown / Not Applicable

  - type: dropdown
    id: scope-package
    attributes:
      label: Package Scope
      description: Which package is affected by this bug? (if applicable)
      options:
        - api
        - arcjet
        - authentication
        - brand
        - chroma-db
        - database
        - environment
        - errors
        - files
        - helpers
        - localization
        - mastra
        - openrouter
        - payment
        - posthog
        - prompts
        - rag
        - redis
        - server-events
        - tavily
        - transactional
        - ui
        - workers
        - Multiple Packages
        - Unknown / Not Applicable

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug here..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major functionality broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      placeholder: "e.g., Node.js 18, Chrome 120, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Which browser are you using?
      placeholder: "e.g., Chrome 120, Firefox 119, Safari 17"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Screenshots, error messages, logs, etc."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply
      options:
        - label: I have searched for similar issues and confirmed this is not a duplicate
        - label: I have tested this on the latest version
        - label: I have included all relevant information (logs, screenshots, etc.)
        - label: I am willing to help test a fix for this issue