name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement
        - UI/UX Improvement
        - Performance Enhancement
        - Integration
        - API Enhancement
        - Configuration Option
        - Documentation Enhancement
        - Accessibility Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope-app
    attributes:
      label: App Scope
      description: Which app is this feature for?
      options:
        - blog
        - dashboard
        - docs
        - landing-page
        - server
        - Multiple Apps
        - Unknown / Not Applicable

  - type: dropdown
    id: scope-package
    attributes:
      label: Package Scope
      description: Which package is this feature for? (if applicable)
      options:
        - api
        - arcjet
        - authentication
        - brand
        - chroma-db
        - database
        - environment
        - errors
        - files
        - helpers
        - localization
        - mastra
        - openrouter
        - payment
        - posthog
        - prompts
        - rag
        - redis
        - server-events
        - tavily
        - transactional
        - ui
        - workers
        - Multiple Packages
        - Unknown / Not Applicable

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: "What's the main goal of this feature?"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem would this feature solve? What's your use case?
      placeholder: "Describe the problem this feature would solve..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or implementation.
      placeholder: "How would you like this feature to work?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: "What other solutions have you considered?"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical for my workflow
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small changes)
        - Medium (moderate changes)
        - Complex (significant changes)
        - Very Complex (major rewrite/refactor)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples.
      placeholder: "Any additional context, mockups, or examples?"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply
      options:
        - label: I have searched for similar feature requests and confirmed this is not a duplicate
        - label: This feature would benefit other users, not just me
        - label: I am willing to help test this feature if implemented
        - label: I am willing to contribute to the implementation of this feature