name: 📝 General Issue
description: For questions, documentation issues, or other general topics
title: "[GENERAL] "
labels: ["question", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 General Issue

        For questions, documentation issues, or other topics that don't fit bug reports or feature requests.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question
        - Documentation Issue
        - Security Concern
        - Performance Issue
        - Configuration Problem
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope-app
    attributes:
      label: App Scope
      description: Which app is this issue related to? (if applicable)
      options:
        - blog
        - dashboard
        - docs
        - landing-page
        - server
        - Multiple Apps
        - Unknown / Not Applicable

  - type: dropdown
    id: scope-package
    attributes:
      label: Package Scope
      description: Which package is this issue related to? (if applicable)
      options:
        - api
        - arcjet
        - authentication
        - brand
        - chroma-db
        - database
        - environment
        - errors
        - files
        - helpers
        - localization
        - mastra
        - openrouter
        - payment
        - posthog
        - prompts
        - rag
        - redis
        - server-events
        - tavily
        - transactional
        - ui
        - workers
        - Multiple Packages
        - Unknown / Not Applicable

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your issue or question in detail.
      placeholder: "Please provide as much detail as possible..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information.
      placeholder: "What were you trying to do? What did you expect?"

  - type: input
    id: environment
    attributes:
      label: Environment (if applicable)
      description: What environment are you running in?
      placeholder: "e.g., Node.js 18, Chrome 120, Ubuntu 22.04"

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information, logs, or screenshots.
      placeholder: "Add any other relevant information here."