name: "Auto-draft PR"
description: "Convert the current PR to draft and comment when a job fails"
runs:
  using: "composite"
  steps:
    - name: Convert PR to draft and comment
      uses: actions/github-script@v7
      with:
        script: |
          if (context.eventName !== 'pull_request') {
            core.info('Not a pull_request event; skipping auto-draft.');
            return;
          }

          const pr = context.payload.pull_request;
          const { owner, repo } = context.repo;

          if (!pr) {
            core.info('No pull_request payload found; skipping.');
            return;
          }

          if (pr.draft) {
            core.info(`PR #${pr.number} already in draft; skipping.`);
            return;
          }

          const prNumber = pr.number;

          try {
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number: prNumber,
              draft: true,
            });

            const wf = context.workflow || 'Workflow';
            const msg = `This PR was automatically converted to draft because checks in "${wf}" failed.\n\nPlease run Nx tests, typecheck, and biome locally and ensure all checks pass before marking this PR as Ready for review again.`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: msg,
            });

            core.info(`Converted PR #${prNumber} to draft and commented.`);
          } catch (error) {
            core.setFailed(`Failed to convert PR to draft: ${error?.message || String(error)}`);
          }
