/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as ShareContentIdRouteImport } from './routes/share/$contentId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAnonymousRouteImport } from './routes/auth/anonymous'
import { Route as SlugOnboardingRouteImport } from './routes/$slug/onboarding'
import { Route as SlugDashboardRouteImport } from './routes/$slug/_dashboard'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthSignInEmailRouteImport } from './routes/auth/sign-in/email'
import { Route as SlugDashboardSettingsRouteImport } from './routes/$slug/_dashboard/settings'
import { Route as SlugDashboardProfileRouteImport } from './routes/$slug/_dashboard/profile'
import { Route as SlugDashboardPlansRouteImport } from './routes/$slug/_dashboard/plans'
import { Route as SlugDashboardOrganizationRouteImport } from './routes/$slug/_dashboard/organization'
import { Route as SlugDashboardManagePlanRouteImport } from './routes/$slug/_dashboard/manage-plan'
import { Route as SlugDashboardHomeRouteImport } from './routes/$slug/_dashboard/home'
import { Route as SlugDashboardWritersIndexRouteImport } from './routes/$slug/_dashboard/writers/index'
import { Route as SlugDashboardSettingsIndexRouteImport } from './routes/$slug/_dashboard/settings/index'
import { Route as SlugDashboardOrganizationIndexRouteImport } from './routes/$slug/_dashboard/organization/index'
import { Route as SlugDashboardContentIndexRouteImport } from './routes/$slug/_dashboard/content/index'
import { Route as CallbackOrganizationInvitationInvitationIdRouteImport } from './routes/callback/organization/invitation.$invitationId'
import { Route as SlugDashboardWritersWriterIdRouteImport } from './routes/$slug/_dashboard/writers/$writerId'
import { Route as SlugDashboardSettingsUsageRouteImport } from './routes/$slug/_dashboard/settings/usage'
import { Route as SlugDashboardSettingsSecurityRouteImport } from './routes/$slug/_dashboard/settings/security'
import { Route as SlugDashboardSettingsProfileRouteImport } from './routes/$slug/_dashboard/settings/profile'
import { Route as SlugDashboardSettingsPreferencesRouteImport } from './routes/$slug/_dashboard/settings/preferences'
import { Route as SlugDashboardSettingsBillingRouteImport } from './routes/$slug/_dashboard/settings/billing'
import { Route as SlugDashboardSettingsApiKeysRouteImport } from './routes/$slug/_dashboard/settings/api-keys'
import { Route as SlugDashboardOrganizationTeamsRouteImport } from './routes/$slug/_dashboard/organization/teams'
import { Route as SlugDashboardOrganizationMembersRouteImport } from './routes/$slug/_dashboard/organization/members'
import { Route as SlugDashboardOrganizationInvitesRouteImport } from './routes/$slug/_dashboard/organization/invites'
import { Route as SlugDashboardContentContentIdRouteImport } from './routes/$slug/_dashboard/content/$contentId'
import { Route as SlugDashboardOrganizationTeamsTeamIdRouteImport } from './routes/$slug/_dashboard/organization/teams/$teamId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareContentIdRoute = ShareContentIdRouteImport.update({
  id: '/share/$contentId',
  path: '/share/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnonymousRoute = AuthAnonymousRouteImport.update({
  id: '/anonymous',
  path: '/anonymous',
  getParentRoute: () => AuthRoute,
} as any)
const SlugOnboardingRoute = SlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardRoute = SlugDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => SlugRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInRoute,
} as any)
const AuthSignInEmailRoute = AuthSignInEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthSignInRoute,
} as any)
const SlugDashboardSettingsRoute = SlugDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardProfileRoute = SlugDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardPlansRoute = SlugDashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardOrganizationRoute =
  SlugDashboardOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardManagePlanRoute = SlugDashboardManagePlanRouteImport.update({
  id: '/manage-plan',
  path: '/manage-plan',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardHomeRoute = SlugDashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardWritersIndexRoute =
  SlugDashboardWritersIndexRouteImport.update({
    id: '/writers/',
    path: '/writers/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardSettingsIndexRoute =
  SlugDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardOrganizationIndexRoute =
  SlugDashboardOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardContentIndexRoute =
  SlugDashboardContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const CallbackOrganizationInvitationInvitationIdRoute =
  CallbackOrganizationInvitationInvitationIdRouteImport.update({
    id: '/callback/organization/invitation/$invitationId',
    path: '/callback/organization/invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlugDashboardWritersWriterIdRoute =
  SlugDashboardWritersWriterIdRouteImport.update({
    id: '/writers/$writerId',
    path: '/writers/$writerId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardSettingsUsageRoute =
  SlugDashboardSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsSecurityRoute =
  SlugDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsProfileRoute =
  SlugDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsPreferencesRoute =
  SlugDashboardSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsBillingRoute =
  SlugDashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsApiKeysRoute =
  SlugDashboardSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardOrganizationTeamsRoute =
  SlugDashboardOrganizationTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardOrganizationMembersRoute =
  SlugDashboardOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardOrganizationInvitesRoute =
  SlugDashboardOrganizationInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardContentContentIdRoute =
  SlugDashboardContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardOrganizationTeamsTeamIdRoute =
  SlugDashboardOrganizationTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => SlugDashboardOrganizationTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugDashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$contentId': typeof ShareContentIdRoute
  '/$slug/home': typeof SlugDashboardHomeRoute
  '/$slug/manage-plan': typeof SlugDashboardManagePlanRoute
  '/$slug/organization': typeof SlugDashboardOrganizationRouteWithChildren
  '/$slug/plans': typeof SlugDashboardPlansRoute
  '/$slug/profile': typeof SlugDashboardProfileRoute
  '/$slug/settings': typeof SlugDashboardSettingsRouteWithChildren
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/$slug/content/$contentId': typeof SlugDashboardContentContentIdRoute
  '/$slug/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/organization/teams': typeof SlugDashboardOrganizationTeamsRouteWithChildren
  '/$slug/settings/api-keys': typeof SlugDashboardSettingsApiKeysRoute
  '/$slug/settings/billing': typeof SlugDashboardSettingsBillingRoute
  '/$slug/settings/preferences': typeof SlugDashboardSettingsPreferencesRoute
  '/$slug/settings/profile': typeof SlugDashboardSettingsProfileRoute
  '/$slug/settings/security': typeof SlugDashboardSettingsSecurityRoute
  '/$slug/settings/usage': typeof SlugDashboardSettingsUsageRoute
  '/$slug/writers/$writerId': typeof SlugDashboardWritersWriterIdRoute
  '/callback/organization/invitation/$invitationId': typeof CallbackOrganizationInvitationInvitationIdRoute
  '/$slug/content': typeof SlugDashboardContentIndexRoute
  '/$slug/organization/': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/settings/': typeof SlugDashboardSettingsIndexRoute
  '/$slug/writers': typeof SlugDashboardWritersIndexRoute
  '/$slug/organization/teams/$teamId': typeof SlugDashboardOrganizationTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugDashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$contentId': typeof ShareContentIdRoute
  '/$slug/home': typeof SlugDashboardHomeRoute
  '/$slug/manage-plan': typeof SlugDashboardManagePlanRoute
  '/$slug/plans': typeof SlugDashboardPlansRoute
  '/$slug/profile': typeof SlugDashboardProfileRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/$slug/content/$contentId': typeof SlugDashboardContentContentIdRoute
  '/$slug/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/organization/teams': typeof SlugDashboardOrganizationTeamsRouteWithChildren
  '/$slug/settings/api-keys': typeof SlugDashboardSettingsApiKeysRoute
  '/$slug/settings/billing': typeof SlugDashboardSettingsBillingRoute
  '/$slug/settings/preferences': typeof SlugDashboardSettingsPreferencesRoute
  '/$slug/settings/profile': typeof SlugDashboardSettingsProfileRoute
  '/$slug/settings/security': typeof SlugDashboardSettingsSecurityRoute
  '/$slug/settings/usage': typeof SlugDashboardSettingsUsageRoute
  '/$slug/writers/$writerId': typeof SlugDashboardWritersWriterIdRoute
  '/callback/organization/invitation/$invitationId': typeof CallbackOrganizationInvitationInvitationIdRoute
  '/$slug/content': typeof SlugDashboardContentIndexRoute
  '/$slug/organization': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/settings': typeof SlugDashboardSettingsIndexRoute
  '/$slug/writers': typeof SlugDashboardWritersIndexRoute
  '/$slug/organization/teams/$teamId': typeof SlugDashboardOrganizationTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/$slug/_dashboard': typeof SlugDashboardRouteWithChildren
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/share/$contentId': typeof ShareContentIdRoute
  '/$slug/_dashboard/home': typeof SlugDashboardHomeRoute
  '/$slug/_dashboard/manage-plan': typeof SlugDashboardManagePlanRoute
  '/$slug/_dashboard/organization': typeof SlugDashboardOrganizationRouteWithChildren
  '/$slug/_dashboard/plans': typeof SlugDashboardPlansRoute
  '/$slug/_dashboard/profile': typeof SlugDashboardProfileRoute
  '/$slug/_dashboard/settings': typeof SlugDashboardSettingsRouteWithChildren
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/$slug/_dashboard/content/$contentId': typeof SlugDashboardContentContentIdRoute
  '/$slug/_dashboard/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/_dashboard/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/_dashboard/organization/teams': typeof SlugDashboardOrganizationTeamsRouteWithChildren
  '/$slug/_dashboard/settings/api-keys': typeof SlugDashboardSettingsApiKeysRoute
  '/$slug/_dashboard/settings/billing': typeof SlugDashboardSettingsBillingRoute
  '/$slug/_dashboard/settings/preferences': typeof SlugDashboardSettingsPreferencesRoute
  '/$slug/_dashboard/settings/profile': typeof SlugDashboardSettingsProfileRoute
  '/$slug/_dashboard/settings/security': typeof SlugDashboardSettingsSecurityRoute
  '/$slug/_dashboard/settings/usage': typeof SlugDashboardSettingsUsageRoute
  '/$slug/_dashboard/writers/$writerId': typeof SlugDashboardWritersWriterIdRoute
  '/callback/organization/invitation/$invitationId': typeof CallbackOrganizationInvitationInvitationIdRoute
  '/$slug/_dashboard/content/': typeof SlugDashboardContentIndexRoute
  '/$slug/_dashboard/organization/': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/_dashboard/settings/': typeof SlugDashboardSettingsIndexRoute
  '/$slug/_dashboard/writers/': typeof SlugDashboardWritersIndexRoute
  '/$slug/_dashboard/organization/teams/$teamId': typeof SlugDashboardOrganizationTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/auth'
    | '/$slug/onboarding'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$contentId'
    | '/$slug/home'
    | '/$slug/manage-plan'
    | '/$slug/organization'
    | '/$slug/plans'
    | '/$slug/profile'
    | '/$slug/settings'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/$slug/content/$contentId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/billing'
    | '/$slug/settings/preferences'
    | '/$slug/settings/profile'
    | '/$slug/settings/security'
    | '/$slug/settings/usage'
    | '/$slug/writers/$writerId'
    | '/callback/organization/invitation/$invitationId'
    | '/$slug/content'
    | '/$slug/organization/'
    | '/$slug/settings/'
    | '/$slug/writers'
    | '/$slug/organization/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/auth'
    | '/$slug/onboarding'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-up'
    | '/share/$contentId'
    | '/$slug/home'
    | '/$slug/manage-plan'
    | '/$slug/plans'
    | '/$slug/profile'
    | '/auth/sign-in/email'
    | '/auth/sign-in'
    | '/$slug/content/$contentId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/settings/api-keys'
    | '/$slug/settings/billing'
    | '/$slug/settings/preferences'
    | '/$slug/settings/profile'
    | '/$slug/settings/security'
    | '/$slug/settings/usage'
    | '/$slug/writers/$writerId'
    | '/callback/organization/invitation/$invitationId'
    | '/$slug/content'
    | '/$slug/organization'
    | '/$slug/settings'
    | '/$slug/writers'
    | '/$slug/organization/teams/$teamId'
  id:
    | '__root__'
    | '/$slug'
    | '/auth'
    | '/$slug/_dashboard'
    | '/$slug/onboarding'
    | '/auth/anonymous'
    | '/auth/callback'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/share/$contentId'
    | '/$slug/_dashboard/home'
    | '/$slug/_dashboard/manage-plan'
    | '/$slug/_dashboard/organization'
    | '/$slug/_dashboard/plans'
    | '/$slug/_dashboard/profile'
    | '/$slug/_dashboard/settings'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/$slug/_dashboard/content/$contentId'
    | '/$slug/_dashboard/organization/invites'
    | '/$slug/_dashboard/organization/members'
    | '/$slug/_dashboard/organization/teams'
    | '/$slug/_dashboard/settings/api-keys'
    | '/$slug/_dashboard/settings/billing'
    | '/$slug/_dashboard/settings/preferences'
    | '/$slug/_dashboard/settings/profile'
    | '/$slug/_dashboard/settings/security'
    | '/$slug/_dashboard/settings/usage'
    | '/$slug/_dashboard/writers/$writerId'
    | '/callback/organization/invitation/$invitationId'
    | '/$slug/_dashboard/content/'
    | '/$slug/_dashboard/organization/'
    | '/$slug/_dashboard/settings/'
    | '/$slug/_dashboard/writers/'
    | '/$slug/_dashboard/organization/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ShareContentIdRoute: typeof ShareContentIdRoute
  CallbackOrganizationInvitationInvitationIdRoute: typeof CallbackOrganizationInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$contentId': {
      id: '/share/$contentId'
      path: '/share/$contentId'
      fullPath: '/share/$contentId'
      preLoaderRoute: typeof ShareContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/anonymous': {
      id: '/auth/anonymous'
      path: '/anonymous'
      fullPath: '/auth/anonymous'
      preLoaderRoute: typeof AuthAnonymousRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/onboarding': {
      id: '/$slug/onboarding'
      path: '/onboarding'
      fullPath: '/$slug/onboarding'
      preLoaderRoute: typeof SlugOnboardingRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/_dashboard': {
      id: '/$slug/_dashboard'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugDashboardRouteImport
      parentRoute: typeof SlugRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/auth/sign-in/email': {
      id: '/auth/sign-in/email'
      path: '/email'
      fullPath: '/auth/sign-in/email'
      preLoaderRoute: typeof AuthSignInEmailRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/$slug/_dashboard/settings': {
      id: '/$slug/_dashboard/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof SlugDashboardSettingsRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/profile': {
      id: '/$slug/_dashboard/profile'
      path: '/profile'
      fullPath: '/$slug/profile'
      preLoaderRoute: typeof SlugDashboardProfileRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/plans': {
      id: '/$slug/_dashboard/plans'
      path: '/plans'
      fullPath: '/$slug/plans'
      preLoaderRoute: typeof SlugDashboardPlansRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization': {
      id: '/$slug/_dashboard/organization'
      path: '/organization'
      fullPath: '/$slug/organization'
      preLoaderRoute: typeof SlugDashboardOrganizationRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/manage-plan': {
      id: '/$slug/_dashboard/manage-plan'
      path: '/manage-plan'
      fullPath: '/$slug/manage-plan'
      preLoaderRoute: typeof SlugDashboardManagePlanRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/home': {
      id: '/$slug/_dashboard/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof SlugDashboardHomeRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/writers/': {
      id: '/$slug/_dashboard/writers/'
      path: '/writers'
      fullPath: '/$slug/writers'
      preLoaderRoute: typeof SlugDashboardWritersIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/settings/': {
      id: '/$slug/_dashboard/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof SlugDashboardSettingsIndexRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/organization/': {
      id: '/$slug/_dashboard/organization/'
      path: '/'
      fullPath: '/$slug/organization/'
      preLoaderRoute: typeof SlugDashboardOrganizationIndexRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/content/': {
      id: '/$slug/_dashboard/content/'
      path: '/content'
      fullPath: '/$slug/content'
      preLoaderRoute: typeof SlugDashboardContentIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/callback/organization/invitation/$invitationId': {
      id: '/callback/organization/invitation/$invitationId'
      path: '/callback/organization/invitation/$invitationId'
      fullPath: '/callback/organization/invitation/$invitationId'
      preLoaderRoute: typeof CallbackOrganizationInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_dashboard/writers/$writerId': {
      id: '/$slug/_dashboard/writers/$writerId'
      path: '/writers/$writerId'
      fullPath: '/$slug/writers/$writerId'
      preLoaderRoute: typeof SlugDashboardWritersWriterIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/settings/usage': {
      id: '/$slug/_dashboard/settings/usage'
      path: '/usage'
      fullPath: '/$slug/settings/usage'
      preLoaderRoute: typeof SlugDashboardSettingsUsageRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/security': {
      id: '/$slug/_dashboard/settings/security'
      path: '/security'
      fullPath: '/$slug/settings/security'
      preLoaderRoute: typeof SlugDashboardSettingsSecurityRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/profile': {
      id: '/$slug/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/$slug/settings/profile'
      preLoaderRoute: typeof SlugDashboardSettingsProfileRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/preferences': {
      id: '/$slug/_dashboard/settings/preferences'
      path: '/preferences'
      fullPath: '/$slug/settings/preferences'
      preLoaderRoute: typeof SlugDashboardSettingsPreferencesRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/billing': {
      id: '/$slug/_dashboard/settings/billing'
      path: '/billing'
      fullPath: '/$slug/settings/billing'
      preLoaderRoute: typeof SlugDashboardSettingsBillingRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/api-keys': {
      id: '/$slug/_dashboard/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$slug/settings/api-keys'
      preLoaderRoute: typeof SlugDashboardSettingsApiKeysRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/organization/teams': {
      id: '/$slug/_dashboard/organization/teams'
      path: '/teams'
      fullPath: '/$slug/organization/teams'
      preLoaderRoute: typeof SlugDashboardOrganizationTeamsRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/organization/members': {
      id: '/$slug/_dashboard/organization/members'
      path: '/members'
      fullPath: '/$slug/organization/members'
      preLoaderRoute: typeof SlugDashboardOrganizationMembersRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/organization/invites': {
      id: '/$slug/_dashboard/organization/invites'
      path: '/invites'
      fullPath: '/$slug/organization/invites'
      preLoaderRoute: typeof SlugDashboardOrganizationInvitesRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/content/$contentId': {
      id: '/$slug/_dashboard/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/$slug/content/$contentId'
      preLoaderRoute: typeof SlugDashboardContentContentIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization/teams/$teamId': {
      id: '/$slug/_dashboard/organization/teams/$teamId'
      path: '/$teamId'
      fullPath: '/$slug/organization/teams/$teamId'
      preLoaderRoute: typeof SlugDashboardOrganizationTeamsTeamIdRouteImport
      parentRoute: typeof SlugDashboardOrganizationTeamsRoute
    }
  }
}

interface SlugDashboardOrganizationTeamsRouteChildren {
  SlugDashboardOrganizationTeamsTeamIdRoute: typeof SlugDashboardOrganizationTeamsTeamIdRoute
}

const SlugDashboardOrganizationTeamsRouteChildren: SlugDashboardOrganizationTeamsRouteChildren =
  {
    SlugDashboardOrganizationTeamsTeamIdRoute:
      SlugDashboardOrganizationTeamsTeamIdRoute,
  }

const SlugDashboardOrganizationTeamsRouteWithChildren =
  SlugDashboardOrganizationTeamsRoute._addFileChildren(
    SlugDashboardOrganizationTeamsRouteChildren,
  )

interface SlugDashboardOrganizationRouteChildren {
  SlugDashboardOrganizationInvitesRoute: typeof SlugDashboardOrganizationInvitesRoute
  SlugDashboardOrganizationMembersRoute: typeof SlugDashboardOrganizationMembersRoute
  SlugDashboardOrganizationTeamsRoute: typeof SlugDashboardOrganizationTeamsRouteWithChildren
  SlugDashboardOrganizationIndexRoute: typeof SlugDashboardOrganizationIndexRoute
}

const SlugDashboardOrganizationRouteChildren: SlugDashboardOrganizationRouteChildren =
  {
    SlugDashboardOrganizationInvitesRoute:
      SlugDashboardOrganizationInvitesRoute,
    SlugDashboardOrganizationMembersRoute:
      SlugDashboardOrganizationMembersRoute,
    SlugDashboardOrganizationTeamsRoute:
      SlugDashboardOrganizationTeamsRouteWithChildren,
    SlugDashboardOrganizationIndexRoute: SlugDashboardOrganizationIndexRoute,
  }

const SlugDashboardOrganizationRouteWithChildren =
  SlugDashboardOrganizationRoute._addFileChildren(
    SlugDashboardOrganizationRouteChildren,
  )

interface SlugDashboardSettingsRouteChildren {
  SlugDashboardSettingsApiKeysRoute: typeof SlugDashboardSettingsApiKeysRoute
  SlugDashboardSettingsBillingRoute: typeof SlugDashboardSettingsBillingRoute
  SlugDashboardSettingsPreferencesRoute: typeof SlugDashboardSettingsPreferencesRoute
  SlugDashboardSettingsProfileRoute: typeof SlugDashboardSettingsProfileRoute
  SlugDashboardSettingsSecurityRoute: typeof SlugDashboardSettingsSecurityRoute
  SlugDashboardSettingsUsageRoute: typeof SlugDashboardSettingsUsageRoute
  SlugDashboardSettingsIndexRoute: typeof SlugDashboardSettingsIndexRoute
}

const SlugDashboardSettingsRouteChildren: SlugDashboardSettingsRouteChildren = {
  SlugDashboardSettingsApiKeysRoute: SlugDashboardSettingsApiKeysRoute,
  SlugDashboardSettingsBillingRoute: SlugDashboardSettingsBillingRoute,
  SlugDashboardSettingsPreferencesRoute: SlugDashboardSettingsPreferencesRoute,
  SlugDashboardSettingsProfileRoute: SlugDashboardSettingsProfileRoute,
  SlugDashboardSettingsSecurityRoute: SlugDashboardSettingsSecurityRoute,
  SlugDashboardSettingsUsageRoute: SlugDashboardSettingsUsageRoute,
  SlugDashboardSettingsIndexRoute: SlugDashboardSettingsIndexRoute,
}

const SlugDashboardSettingsRouteWithChildren =
  SlugDashboardSettingsRoute._addFileChildren(
    SlugDashboardSettingsRouteChildren,
  )

interface SlugDashboardRouteChildren {
  SlugDashboardHomeRoute: typeof SlugDashboardHomeRoute
  SlugDashboardManagePlanRoute: typeof SlugDashboardManagePlanRoute
  SlugDashboardOrganizationRoute: typeof SlugDashboardOrganizationRouteWithChildren
  SlugDashboardPlansRoute: typeof SlugDashboardPlansRoute
  SlugDashboardProfileRoute: typeof SlugDashboardProfileRoute
  SlugDashboardSettingsRoute: typeof SlugDashboardSettingsRouteWithChildren
  SlugDashboardContentContentIdRoute: typeof SlugDashboardContentContentIdRoute
  SlugDashboardWritersWriterIdRoute: typeof SlugDashboardWritersWriterIdRoute
  SlugDashboardContentIndexRoute: typeof SlugDashboardContentIndexRoute
  SlugDashboardWritersIndexRoute: typeof SlugDashboardWritersIndexRoute
}

const SlugDashboardRouteChildren: SlugDashboardRouteChildren = {
  SlugDashboardHomeRoute: SlugDashboardHomeRoute,
  SlugDashboardManagePlanRoute: SlugDashboardManagePlanRoute,
  SlugDashboardOrganizationRoute: SlugDashboardOrganizationRouteWithChildren,
  SlugDashboardPlansRoute: SlugDashboardPlansRoute,
  SlugDashboardProfileRoute: SlugDashboardProfileRoute,
  SlugDashboardSettingsRoute: SlugDashboardSettingsRouteWithChildren,
  SlugDashboardContentContentIdRoute: SlugDashboardContentContentIdRoute,
  SlugDashboardWritersWriterIdRoute: SlugDashboardWritersWriterIdRoute,
  SlugDashboardContentIndexRoute: SlugDashboardContentIndexRoute,
  SlugDashboardWritersIndexRoute: SlugDashboardWritersIndexRoute,
}

const SlugDashboardRouteWithChildren = SlugDashboardRoute._addFileChildren(
  SlugDashboardRouteChildren,
)

interface SlugRouteChildren {
  SlugDashboardRoute: typeof SlugDashboardRouteWithChildren
  SlugOnboardingRoute: typeof SlugOnboardingRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugDashboardRoute: SlugDashboardRouteWithChildren,
  SlugOnboardingRoute: SlugOnboardingRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthSignInRouteChildren {
  AuthSignInEmailRoute: typeof AuthSignInEmailRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInEmailRoute: AuthSignInEmailRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthRouteChildren {
  AuthAnonymousRoute: typeof AuthAnonymousRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnonymousRoute: AuthAnonymousRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ShareContentIdRoute: ShareContentIdRoute,
  CallbackOrganizationInvitationInvitationIdRoute:
    CallbackOrganizationInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
