name: "Setup Bun & Nx"
description: "Setup Bun, install dependencies, cache, and configure Nx"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.23

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash

    - name: Set Nx SHAs
      uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: master

