name: Auto-draft PRs on failing checks

on:
  workflow_run:
    workflows:
      - Tests
      - Biome check
      - Typescript typechecking
    types:
      - completed

jobs:
  auto-draft:
    if: >-
      ${{ github.event.workflow_run.event == 'pull_request' && contains(fromJson('["failure","timed_out","cancelled"]'), github.event.workflow_run.conclusion) }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Convert PR to draft and comment
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const [owner, repo] = run.repository.full_name.split('/');

            // Pull requests associated with this workflow run
            let prs = run.pull_requests || [];

            // Fallback: find PR by head branch if none are attached
            if (!prs.length) {
              const headOwner = run.head_repository?.owner?.login || owner;
              const headRef = run.head_branch;
              if (headRef) {
                const { data: list } = await github.rest.pulls.list({
                  owner,
                  repo,
                  state: 'open',
                  head: `${headOwner}:${headRef}`,
                });
                prs = list;
              }
            }

            if (!prs.length) {
              core.info('No associated pull requests found for this workflow run.');
              return;
            }

            for (const pr of prs) {
              if (pr.draft) {
                core.info(`PR #${pr.number} already in draft; skipping.`);
                continue;
              }

              // Convert to draft
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: pr.number,
                draft: true,
              });

              // Leave a comment
              const msg = `This PR was automatically converted to draft because required checks failed (${run.name}).\n\nPlease run tests, typecheck, and biome locally and ensure all checks pass before marking this PR as Ready for review again.`;
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body: msg,
              });
            }
