name: Auto-draft PRs on failing checks

on:
  workflow_run:
    workflows:
      - Tests
      - Biome check
      - Typescript typechecking
    types:
      - completed

jobs:
  auto-draft:
    if: >-
      ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Convert PR to draft and comment
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const [owner, repo] = run.repository.full_name.split('/');

            // Fetch PRs associated with this workflow run
            const { data: prs } = await github.request(run.pull_requests_url);

            for (const pr of prs) {
              // Convert to draft
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: pr.number,
                draft: true,
              });

              // Leave a comment
              const msg = "This PR was automatically converted to draft because required checks failed (" + run.name + ").\n\nPlease run tests, typecheck, and biome locally and ensure all checks pass before marking this PR as Ready for review again.";
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr.number,
                body: msg,
              });
            }
