name: Auto-draft new PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-draft:
    name: Mark and comment
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Mark PR as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Thanks for opening this PR! 

            This PR has been automatically marked as draft to ensure quality and prevent accidental merges.

            **Before marking this PR as "Ready for review":**
            - ✅ Make sure all your changes are complete
            - ✅ Run tests locally: `bunx nx affected -t test`
            - ✅ Run typecheck locally: `bunx nx affected -t typecheck`
            - ✅ Run lint/format checks: `bunx nx affected -t check`
            - ✅ Review your changes one more time

            **When you're 100% confident everything is ready**, click "Ready for review" to trigger the automated checks.

            If checks fail, the PR will be automatically converted back to draft with specific guidance on what needs to be fixed.
