name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  tests:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx
      - name: Run Nx affected tests
        run: bunx nx affected -t test --base=origin/master --head=HEAD

  typecheck:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx
      - name: Run Nx affected typecheck
        run: bunx nx affected -t typecheck --base=origin/master --head=HEAD

  biome_check:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx
      - name: Run Nx affected check
        run: bunx nx affected -t check --base=origin/master --head=HEAD

  convert_to_draft:
    name: Convert PR to Draft (on failure)
    needs: [tests, typecheck, biome_check]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Convert PR to Draft
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        uses: yu-iskw/convert-to-draft-action@v0.4.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          leave_comment: "1"
          comment_body: |
            This PR was automatically converted to draft because required checks (Tests / Typecheck / Biome) did not pass.

            Please run locally and fix issues:
            - Tests: `bunx nx affected -t test`
            - Typecheck: `bunx nx affected -t typecheck`
            - Biome: `bunx nx affected -t check`

            Mark as "Ready for review" after everything passes.
