name: PR CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun-nx
      - run: bunx nx affected -t test --base=origin/master --head=HEAD

  typecheck:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun-nx
      - run: bunx nx affected -t typecheck --base=origin/master --head=HEAD

  biome_check:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun-nx
      - run: bunx nx affected -t check --base=origin/master --head=HEAD

  convert_to_draft:
    name: Convert PR to Draft (on failure)
    needs: [tests, typecheck, biome_check]
    if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Leave failure guidance comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This PR was automatically converted to draft because required checks (Tests / Typecheck / Biome) did not pass.

            Please run locally and fix issues:
            - Tests: `bunx nx affected -t test`
            - Typecheck: `bunx nx affected -t typecheck`
            - Biome: `bunx nx affected -t check`

            Mark as "Ready for review" after everything passes.
