name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # Example check jobs (rename to match real jobs)
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # run tests...
      - run: echo "run tests here"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # run typecheck...
      - run: echo "run typecheck here"

  biome_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # run biome/lint...
      - run: echo "run lint/checks here"

  convert_to_draft:
    name: Convert PR to Draft (on failure)
    needs: [tests, typecheck, biome_check]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Convert PR to Draft
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        uses: yu-iskw/convert-to-draft-action@v0.4.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          leave_comment: "1"
          comment_body: |
            This PR was automatically converted to draft because Biome check failed.

            Please run `bunx nx affected -t check` locally and ensure all checks pass before marking this PR as Ready for review again.
