name: Biome check

on:

  pull_request:
    branches: ["*"]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          



      - name: Get Bun version
        id: bun-version
        run: echo "version=$(bun --version)" >> $GITHUB_OUTPUT

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ steps.bun-version.outputs.version }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Connect to Nx Cloud
        run: npx nx connect

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4



      - name: Run Nx affected check
        run: npx nx affected -t check --base=origin/master --head=HEAD

      - name: Self-Healing CI
        run: npx nx-cloud fix-ci
        if: always()
