name: PR Comment on Typecheck Failure

on:
  workflow_run:
    workflows:
      - "Typecheck"
      - "Tests"
      - "Biome Check" 
    types:
      - completed

permissions:
  contents: read
  issues: write

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = context.payload.workflow_run;
            const prs = run.pull_requests || [];
            if (!prs.length) return;
            
            const prNumber = prs[0].number;
            const body = `## ❌ ${run.name} Failed
            
            The workflow failed. Please:
            1. Run locally: \`bunx nx affected -t typecheck --base=origin/master --head=HEAD\`

            2. Fix all issues
            3. **Convert this PR to draft** until checks pass
            4. Mark as "Ready for review" when done

            [Convert to Draft](https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${prNumber})`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body
            });
