name: Conventional Commits Check

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  conventional-commits-check:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Check conventional commits
        run: |
          # Get the list of commits in this PR
          COMMITS=$(git rev-list --no-merges origin/master...HEAD)
          
          # Check each commit using commitlint
          for commit in $COMMITS; do
            echo "Checking commit: $commit"
            if ! npx commitlint --from $commit --to $commit; then
              echo "❌ Commit $commit does not follow the conventional commits format or has invalid scope"
              echo ""
              echo "Commit message:"
              git log --format=%B -n 1 $commit
              echo ""
              echo "Valid scopes are: blog, dashboard, docs, landing-page, server, agents, api, authentication, brand, database, environment, files, localization, payment, posthog, rag, server-events, transactional, ui, utils, workers, typescript, deps, build, ci, release, chore"
              echo ""
              echo "Example format: feat(rag): add new embedding functionality"
              exit 1
            fi
          done
          
          echo "✅ All commits follow conventional commits format with valid scopes"

      