name: Label PRs Based on Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened,]

jobs:
  label-by-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Label PR based on conventional commit title
        uses: actions/github-script@v7
        with:
          script: |
            const { context } = github;
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            
            const labels = [];
            
            // Check for conventional commit patterns
            const conventionalCommitMatch = prTitle.match(/^(\w+)(\(.+\))?:/);
            
            if (conventionalCommitMatch) {
              const type = conventionalCommitMatch[1].toLowerCase();
              
              // Map conventional commit types to labels
              switch (type) {
                case 'feat':
                  labels.push('feature', 'enhancement');
                  break;
                case 'fix':
                  labels.push('bug', 'fix');
                  break;
                case 'docs':
                  labels.push('documentation');
                  break;
                case 'style':
                  labels.push('style');
                  break;
                case 'refactor':
                  labels.push('refactor');
                  break;
                case 'test':
                  labels.push('test');
                  break;
                case 'chore':
                  labels.push('chore');
                  break;
                case 'perf':
                  labels.push('performance');
                  break;
                case 'ci':
                  labels.push('ci');
                  break;
                case 'build':
                  labels.push('build');
                  break;
                default:
                  // For unknown types, add a generic label
                  labels.push('needs-triage');
              }
            } else {
              // If title doesn't follow conventional commits, add triage label
              labels.push('needs-triage');
            }
            
            // Add size label based on files changed
            const filesChanged = context.payload.pull_request.changed_files;
            if (filesChanged <= 3) {
              labels.push('size/S');
            } else if (filesChanged <= 10) {
              labels.push('size/M');
            } else if (filesChanged <= 25) {
              labels.push('size/L');
            } else {
              labels.push('size/XL');
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
            }
