name: Automated Release

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Perform release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Perform the release
          bun run release -- --first-release

      - name: Summary
        run: |
          echo "✅ Release completed successfully!"
          echo "📝 Changelog and GitHub release created"
          echo "🏷️  Git tag created and pushed"