name: Bun Security Audit

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Bun audit (capture output)
        id: audit
        run: |
          # Run audit but never fail the job; capture output
          bun audit || true > audit.txt
          echo "Audit output saved to audit.txt"

      - name: Build PR comment body (safe quoting)
        run: |
          {
            echo "### 🔒 Bun Security Audit"
            echo
            echo "Repository: ${{ github.repository }}  "
            echo "Ref: \`${{ github.ref }}\`"
            echo
            echo "#### Results"
            echo
            echo '```
            cat audit.txt
            echo '```'
            echo
            echo "_Tip: run \`bun audit\` locally and update vulnerable dependencies if needed._"
          } > audit-comment.md

      - name: Comment audit results on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: audit-comment.md
