name: Bun Security Audit

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  audit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Bun audit (capture output)
        run: |
         bun audit > audit.txt 2>&1 || true

      - name: Build PR comment body (heredoc, safe)
        run: |
          cat > audit-comment.md << 'EOF'
          ### 🔒 Bun Security Audit

          Repository: ${{ github.repository }}  
          Ref: `${{ github.ref }}`

          #### Results

          ```
          EOF
          cat audit.txt >> audit-comment.md
          cat >> audit-comment.md << 'EOF'
          ```

          _Tip: run `bun audit` locally and update vulnerable dependencies if needed._
          EOF

      - name: Comment audit results on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: audit-comment.md
