name: Run tests

on:
  pull_request:
    branches: ["*"]

jobs:
  check:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Run Nx affected test
        run: npx nx affected -t test --base=origin/master --head=HEAD
