name: Tests

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Run Nx affected tests
        run: bunx nx affected -t test --base=origin/master --head=HEAD

      - name: Check workflow status and comment
        if: ${{ failure() }}
        uses: ./.github/actions/check-workflows
        with:
          workflow_name: "Tests"
          command: "bunx nx affected -t test --base=origin/master --head=HEAD"
