name: Typescript typechecking

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Run Nx affected typecheck
        run: bunx nx affected -t typecheck --base=origin/master --head=HEAD

      - name: Auto-draft PR on failure
        if: ${{ failure() }}
        uses: alexesprit/action-pr-to-draft@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on PR
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            if (context.eventName !== 'pull_request') return;
            const pr = context.payload.pull_request;
            if (!pr || pr.draft) return;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: 'This PR was automatically converted to draft because typecheck failed.\n\nPlease run `bunx nx affected -t typecheck` locally and ensure all checks pass before marking this PR as Ready for review again.'
            });
