name: TypeScript Typechecking

on:
  pull_request:
    types: [ready_for_review]  # Only trigger when PR is marked ready

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Bun & Nx Setup
        uses: ./.github/actions/setup-bun-nx

      - name: Run Nx affected typecheck
        run: bunx nx affected -t typecheck --base=origin/master --head=HEAD
